# Generated by Django 2.1 on 2018-08-28 12:50

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180828_0553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='generated_labels',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(null=True), null=True, size=None),
        ),
    ]
