# Generated by Django 2.1 on 2018-08-29 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20180828_1255'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probability', models.CharField(max_length=256)),
                ('prediction', models.CharField(max_length=256)),
            ],
        ),
        migrations.RemoveField(
            model_name='dog',
            name='generated_labels',
        ),
        migrations.AddField(
            model_name='label',
            name='dog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_labels', to='api.Dog'),
        ),
    ]
